import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function UserLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  console.log("in");
  return (
    <div className="flex h-full">
      {/* Sidebar */}
      <div className="w-2/12 bg-red-100">
        <h1 className="sidebar">Sidebar</h1>
      </div>
      {/* COntent */}
      <div className="w-10/12 bg-green-100">
        {/* Navbar */}
        <div className="bg-blue-100">
          <h1>Navbar</h1>
        </div>
        <div className="bg-white h-full">{children}</div>
      </div>
    </div>
  );
}

// User can click a button and then the user will log out
//step 1 create button
//step 2 button triggers function that erases jwt token from localstorage, user object gets cleared from state
//step 3 redirect to login
